version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/hello-world-java
file_exists_behavior: OVERWRITE
hooks:      
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ubuntu
