version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto19
  pre_build:
    commands:
      - echo installing
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo build completed
artifacts:
  files:
    - appspec.yml
    - target/my-app.jar
    - script/
    - '**/*'
